### PR TITLE
Feat: Add features for #87

### PR DESCRIPTION
**Pull request by seungki1011**
Github issue #87

## PR Type

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

### CODE REVIEW

**Comment by CheonJiEun** [comment]
확인했습니다!

**Comment by Eyecaramba** [comment]
확인했습니다!

**Comment by helpmeIamnewbie** [comment]
확인했습니다!

**Comment by jjjuuuun** [comment]
확인했습니다!

**Pull request merged**
